/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        final Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
